version: "3.3"

services:
  seq:
    container_name: dotnet_architecture_seq
    image: datalust/seq:latest
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
      - SEQ_API_KEY=uniqueapikey
    volumes:
      - dotnet_architecture-dev-seq:/data
  rabbitmq:
    container_name: dotnet_architecture_rabbitmq
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_ERLANG_COOKIE=uniqueerlangcookie
    volumes:
      - dotnet_architecture-dev-rabbitmq:/var/lib/rabbitmq/mnesia

volumes:
  dotnet_architecture-dev-seq:
  dotnet_architecture-dev-rabbitmq:
